services:
  frontend:
    build:
      context: ./urugo-woc-app
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    volumes:
      - ./urugo-woc-app:/app
      - /app/node_modules
    container_name: ftd-dev
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    container_name: api-dev
    restart: unless-stopped
    environment:
      - DEBUG=1
