version: '3.8'

services:
  frontend:
    build:
      context: ./urugo-woc-app
      dockerfile: DockerFile.prod
    ports:
      - "8081:80"
    volumes:
      - ./urugo-woc-app:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=api_settings.production
    restart: unless-stopped