version: '3.8'

services:
  frontend:
    build:
      context: ./urugo-woc-app
      dockerfile: DockerFile.prod
    ports:
      - "5173:5173"
    volumes:
      - ./urugo-woc-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    command: npm run build && npm run serve

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=api.settings
    restart: unless-stopped
    networks:
      - app-network
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000

networks:
  app-network:
    driver: bridge
