# Generated by Django 5.1.6 on 2025-02-24 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donation_item_alter_user_phone_number_blogpost_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\\\+?1?\\\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
