# Generated by Django 5.1.6 on 2025-02-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_donation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, null=True, verbose_name='social links'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('user', 'User'), ('ustaff', 'User Staff')], default='user', max_length=20, verbose_name='role'),
        ),
    ]
