# Generated by Django 5.1.6 on 2025-02-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_account_active_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
