# Generated by Django 5.1.6 on 2025-02-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_blogpost_post_rename_item_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Listing',
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'listing', 'verbose_name_plural': 'listings'},
        ),
    ]
