# Generated by Django 5.1.6 on 2025-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_partner_alter_listing_image_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('happening', 'Happening'), ('upcoming', 'Upcoming'), ('archived', 'Archived')], default='published', max_length=20, verbose_name='status'),
        ),
    ]
