# Generated by Django 5.1.6 on 2025-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('single', 'Single'), ('couple', 'Couple')], max_length=100, null=True, verbose_name='category'),
        ),
    ]
