# Generated by Django 5.1.6 on 2025-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='dining/')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
