# Generated by Django 5.1.6 on 2025-02-26 17:48

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dining',
            options={'verbose_name': 'dining', 'verbose_name_plural': 'dinings'},
        ),
        migrations.AddField(
            model_name='dining',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dining',
            name='category',
            field=models.CharField(
                blank=True, 
                choices=[
                    ('african_dish', 'African Dish'), 
                    ('kinyarwanda_dish', 'Kinyarwanda Dish'), 
                    ('african_culture', 'African Culture')
                ], 
                max_length=100, 
                null=True, 
                verbose_name='category'
            ),
        ),
        migrations.AddField(
            model_name='dining',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
