# Generated by Django 5.1.6 on 2025-02-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dining_short_description_listing_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dining',
            old_name='short_description',
            new_name='short_desc',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='short_description',
            new_name='short_desc',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='short_description',
            new_name='short_desc',
        ),
    ]
