# Generated by Django 5.1.6 on 2025-02-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_name_dining_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
