# Generated by Django 5.1.6 on 2025-02-26 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_name_listing_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveIntegerField()),
                ('booking_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dining')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dining booking',
                'verbose_name_plural': 'dining bookings',
            },
        ),
    ]
